version: '3'
services:
  auth:
    build: ./server/ms-auth
    restart: always
    hostname: auth
    expose:
      - "3001"
    ports:
      - "3001:3001"
    networks:
      - backend
    volumes:
      - ./data:/var/www/server/ms-auth/data
    # links:
    #   - db
  game:
    build: ./server/ms-game
    restart: always
    hostname: game
    expose:
      - "3002"
    ports:
      - "3002:3002"
    networks:
      - backend
    volumes:
      - ./data:/var/www/server/ms-game/data
    # links:
    #   - db
  stat:
    build: ./server/ms-stat
    restart: always
    hostname: stat
    expose:
      - "3003"
    ports:
      - "3003:3003"
    networks:
      - backend
    volumes:
      - ./data:/var/www/server/ms-stat/data
    # links:
    #   - db
  client:
    build: ./server/ms-client
    restart: always
    hostname: api
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - backend
  app:
    build: ./app
    restart: always
    hostname: app
    expose:
      - "4200"
    ports:
      - "4200:4200"
    networks:
      - backend
    # links:
    #   - db
networks:
  backend:
    driver: bridge